# Generated by Django 6.0 on 2026-01-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=75, verbose_name='First Name')),
                ('l_name', models.CharField(max_length=75, verbose_name='Last Name')),
                ('color_code', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(verbose_name='Publication Date'),
        ),
    ]
