# Generated by Django 6.0 on 2026-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_blog_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Group Nsme')),
                ('members', models.ManyToManyField(related_name='groups', to='books.person')),
            ],
        ),
    ]
