# Generated by Django 6.0 on 2026-01-02 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composite_key', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForiegnObjectExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_order_id', models.CharField(max_length=20)),
                ('item_product_id', models.IntegerField()),
                ('item', models.ForeignObject(from_fields=('item_order_id', 'item_product_id'), on_delete=django.db.models.deletion.CASCADE, to='composite_key.orderlineitem', to_fields=('order_id', 'product_id'))),
            ],
        ),
    ]
