# Generated by Django 6.0 on 2026-01-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('composite_key', '0002_foriegnobjectexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
            ],
        ),
    ]
