# Generated by Django 6.0 on 2026-01-07 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagination', '0002_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='no',
            field=models.FloatField(default=0),
        ),
    ]
